// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjh0yo4BSbnX2pKKo3fVFNDYfmueRMcFE',
    appId: '1:117958949462:web:95e0ed6ecf196689ef19f7',
    messagingSenderId: '117958949462',
    projectId: 'soccerapp-1b46a',
    authDomain: 'soccerapp-1b46a.firebaseapp.com',
    databaseURL: 'https://soccerapp-1b46a-default-rtdb.firebaseio.com',
    storageBucket: 'soccerapp-1b46a.appspot.com',
    measurementId: 'G-X4FG7JY2T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrQO59x7kINECrYYeDOk1ORXbT79RMMMw',
    appId: '1:117958949462:android:4944e47580353970ef19f7',
    messagingSenderId: '117958949462',
    projectId: 'soccerapp-1b46a',
    databaseURL: 'https://soccerapp-1b46a-default-rtdb.firebaseio.com',
    storageBucket: 'soccerapp-1b46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CLRBZ1W44JYx-1sz1gAvd3dSCcMG6V8',
    appId: '1:117958949462:ios:b9001d3c2275ce69ef19f7',
    messagingSenderId: '117958949462',
    projectId: 'soccerapp-1b46a',
    databaseURL: 'https://soccerapp-1b46a-default-rtdb.firebaseio.com',
    storageBucket: 'soccerapp-1b46a.appspot.com',
    androidClientId: '117958949462-uetiavbpmaqto2f83haaqt3ofnj6h2c3.apps.googleusercontent.com',
    iosClientId: '117958949462-96f96jg8v56lj7n0mo7ls1ep6l0hbqef.apps.googleusercontent.com',
    iosBundleId: 'com.samtech.soccerLifeRelease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CLRBZ1W44JYx-1sz1gAvd3dSCcMG6V8',
    appId: '1:117958949462:ios:d1b75a29cd8ecdfcef19f7',
    messagingSenderId: '117958949462',
    projectId: 'soccerapp-1b46a',
    databaseURL: 'https://soccerapp-1b46a-default-rtdb.firebaseio.com',
    storageBucket: 'soccerapp-1b46a.appspot.com',
    androidClientId: '117958949462-uetiavbpmaqto2f83haaqt3ofnj6h2c3.apps.googleusercontent.com',
    iosClientId: '117958949462-08evvmv52pdvlrpk1iboesfnp9i4bfpu.apps.googleusercontent.com',
    iosBundleId: 'com.samtech.soccerLifeRelease.RunnerTests',
  );
}
