// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3sSw112jSLPqS3f3Lo_9GO-sTDw02kY',
    appId: '1:213948590313:web:2efe177dcfe94770b66878',
    messagingSenderId: '213948590313',
    projectId: 'soccer-20d83',
    authDomain: 'soccer-20d83.firebaseapp.com',
    storageBucket: 'soccer-20d83.appspot.com',
    measurementId: 'G-5NLRM6S8SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxAti0UuJf8HoybLWd0vy8ZAKz7n7VCg',
    appId: '1:213948590313:android:c1cd02bc6f73ebf1b66878',
    messagingSenderId: '213948590313',
    projectId: 'soccer-20d83',
    storageBucket: 'soccer-20d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MeGN7uj2y-4n3ZA1uhryDaB_tmMS8kw',
    appId: '1:213948590313:ios:15837b40c92bd5e6b66878',
    messagingSenderId: '213948590313',
    projectId: 'soccer-20d83',
    storageBucket: 'soccer-20d83.appspot.com',
    iosClientId: '213948590313-a10hv4ien1bbb0g71sqj4ki3b3fstlbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.soccer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_MeGN7uj2y-4n3ZA1uhryDaB_tmMS8kw',
    appId: '1:213948590313:ios:8568ff7a3bb08eccb66878',
    messagingSenderId: '213948590313',
    projectId: 'soccer-20d83',
    storageBucket: 'soccer-20d83.appspot.com',
    iosClientId: '213948590313-jp1ahts6rvbhmdf1900oqilojg1nj0gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.soccer.RunnerTests',
  );
}
